### ISSUE TITLE
v0.1 Roadmap

### ISSUE THREAD

**Issue by swarmer** [swarmer/depchecker#1]
- [x] conformance to requirements.txt
- [x] unneeded packages
- [x] additional info in conflicts
- [x] vulnerabilities
- [x] choosing env other than current
- [x] consistency between all installed packages
